### ISSUE TITLE
 Illegal string offset 'id'

### ISSUE THREAD

**Issue by unwiredtech** [strangerstudios/pmpro-aweber#14]
**I get this error when I delete a user & registering a new user.**

`
Warning: Illegal string offset 'id' in /var/sites/t/site.com/public_html/wp-content/plugins/pmpro-aweber/pmpro-aweber.php on line 221

Warning: Cannot modify header information - headers already sent by (output started at /var/sites/t/site.com/public_html/wp-content/plugins/pmpro-aweber/pmpro-aweber.php:221) in /var/sites/t/site.com.com/public_html/wp-includes/pluggable.php on line 1228
`

**Comment by strangerstudios** [comment]
v1.2 going out today includes some updates so the subscribe methods can accept arrays or single list ids. It should prevent this warning. If you are still getting it, please open a new issue. Thanks.
