### ISSUE TITLE
Users are not changed to new level

### ISSUE THREAD

**Issue by unwiredtech** [strangerstudios/pmpro-aweber#16]
When moving/upgrading a user to next level, the user is not added to the new level list.

**Comment by strangerstudios** [comment]
They may have to confirm by email again. You can reach out to AWeber about removing the double opt in requirement.

**Comment by dparker1005** [comment]
As we have not heard back to you, I am going to close this issue. If this is behavior that you are still experiencing on your site, please feel free to open a new issue in this repository.
