### ISSUE TITLE
Uncaught Error: Class 'AWeberAPI' not found on AfiliateWP regististration?

### ISSUE THREAD

**Issue by KingNet** [strangerstudios/pmpro-aweber#17]
When i edit Affiliates on AffiliateWP plugin or submit new registration from frontend in affiliate area i get "500 error" first, than i turn debug on and than i get :

> Fatal error: Uncaught Error: Class 'AWeberAPI' not found in /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-content/plugins/pmpro-aweber/pmpro-aweber.php:87 Stack trace: #0 /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-content/plugins/pmpro-aweber/pmpro-aweber.php(312): pmproaw_getAccount() #1 /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-includes/plugin.php(525): pmproaw_profile_update(1, Object(WP_User)) #2 /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-includes/user.php(1661): do_action('profile_update', 1, Object(WP_User)) #3 /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-includes/user.php(1761): wp_insert_user(Array) #4 /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-content/plugins/affiliate-wp/includes/class-register.php(263): wp_update_user(Array) #5 /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-content/plugins/affiliate-wp/includes/class-register.php(144): Affiliate_WP_Register->register_ in /home/test.cloudwaysapps.com/zzazfhvsnt/public_html/wp/wp-content/plugins/pmpro-aweber/pmpro-aweber.php on line 87

When i deactivate pmpro-aweber plugin, than it works fine.

NOTE: I am using PHP 7. 
Inside pmproaw_init you call AWeberAPI from 

> /includes/aweber_api/aweber_api.php

 if class not exists. AWeberAPI class is in aweber.php,
I solve it now with adding 

```
if(!class_exists("AWeberAPI"))
{
    require_once(dirname(__FILE__) . "/includes/aweber_api/aweber_api.php");
}
```

inside pmproaw_getAccount function in pmpro-aweber.php file, in try block. Please fix this in next update. It looks like pmpro-aweber is not initalized from affiliatewp plugin, that is why i fix this by adding following code.

**Comment by strangerstudios** [comment]
AffiliateWP uses the same AWeber API. v1.2 has the latest version of their PHP API library. Hopefully AffiliateWP is also up to date and this works. Alternatively, you can follow up with AffiliateWP RE updating the API version they are using.

**Comment by strangerstudios** [comment]
btw, we have the if(!class_exists...) line in our code now. I suspect AffiliateWP has that one as well.

**Comment by dparker1005** [comment]
As we have not heard back to you, I am going to close this issue. If this is behavior that you are still experiencing on your site, please feel free to open a new issue in this repository.
