### ISSUE TITLE
Can't save changes without having chosen an All Users List

### ISSUE THREAD

**Issue by jacobshare** [strangerstudios/pmpro-aweber#21]
After creating a new Membership Level, I wanted to assign it an Aweber list via this add-on. I've done this successfully twice in the past and it worked as expected.

However, this time, this Add On refused to save my change.

Through testing, I discovered that an All Users List must now be selected. Only then can I save changes in this Add On. However, I haven't been using an All Users List until now because my Levels' subscribers are unrelated.

I think this issue was introduced with version 1.3.

**Comment by dparker1005** [comment]
Hi @jacobshare,

This issue should have been addressed by PMPro AWeber v1.3.1. Thank you for reporting that issue.
