### ISSUE TITLE
Subscriber update fails in `pmproaw_subscribe()`

### ISSUE THREAD

**Issue by dparker1005** [strangerstudios/pmpro-aweber#25]
Every time that `pmproaw_subscribe()` is called, it tries to create a new subscriber in AWeber. If a subscriber with the same email already exists, the call to create a new one fails. This causes a couple of issues:
- Users who have been removed from the list from losing a membership level and then regain that membership level will not be added back into list
- `pmpro_aweber_custom_fields` filter will not have an affect when user changes/renews membership level

The solution would be to have two branches in that function: one if the subscriber exists in the AWeber list and one if they do not exist.

If they do already exist, we should:
- Get the subscriber object (as in `pmproaw_unsubscribe()`)
- Set the status to 'subscribed'
- Update custom fields if `pmpro_aweber_custom_fields` filter does not return empty
- Save the subscriber

If they do not already exist, we should do what we are currently doing.

**Comment by ermGit** [comment]
There is a easier way to fix this.

```
	if (!$custom_fields = apply_filters("pmpro_aweber_custom_fields", array(), $list_user))
	{
		$new_subscriber = $subscribers->create(array(
				'email' => $list_user->user_email,
			        'name' => trim($list_user->first_name . " " . $list_user->last_name),
                                'update_existing' => true,
                                'status' => 'subscribed',
                ));
	}
	
	else
	{
		$new_subscriber = $subscribers->create(array(
				'email' => $list_user->user_email,
				'name' => trim($list_user->first_name . " " . $list_user->last_name),
                                'update_existing' => true,
                                'status' => 'subscribed',
				'custom_fields' => $custom_fields,
                ));
	}
```
