### ISSUE TITLE
Unable to connect to the AWeber API

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-aweber#39]
**Describe the bug**
You are unable to connect to AWeber.

**To Reproduce**
1. Go to Settings > PMPro AWeber Integration Options
2. Connect to AWeber 
4. See error - 

> AWeberAPIException:
> Type: APIUnreachableError
> Msg : Unable to connect to the AWeber API. ()
> Docs: https://labs.aweber.com/docs/troubleshooting 

**Screenshot**
![image](https://github.com/strangerstudios/pmpro-aweber/assets/4752949/e3477ee5-6e7f-4d43-9d59-2553afe3ffc7)

**Expected behavior**
You should be able to connect. 

This came up in ticket (ID 507419) and I could replicate.

**Isolating the problem:**
- [x] I have deactivated other plugins and confirmed this bug occurs when only Paid Memberships Pro plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Memberlite](https://wordpress.org/themes/memberlite/).
- [x] I can reproduce this bug consistently using the steps above.

**WordPress Environment**
<details>
```
Paid Memberships Pro 2.11.2, AWeber Add On 1.3.3, WordPress 6.2.2, PHP 7.4.30 
```
</details>

**Comment by andrewlimaza** [comment]
Adding some notes here:

* Aweber API won't ever authenticate with localWP or any locally hosted site. There's been a change to Aweber's API and testing Aweber will require a live site with a public domain.
* Try generate a new key/oAuth if you're facing this issue. Try at different times of the day.
* Reach out to Aweber's support to see if they can provide a more detailed error from their end (🤞)
* This only affecting _some_ sites. (It was happening on my account last week, but now it's cleared up - not sure if there was an outage or a "block" on my account for some reason).
* V1.3.3 does not change any functionality, it stops a fatal error that was happening on earlier versions.

**Comment by michaelbeil** [comment]
This error is fixed when I reconnected with a new authorization code.

**Comment by michaelbeil** [comment]
This was resolved for a customer.
>It seems to be working again.
