### ISSUE TITLE
No exception handling in pmproaw_profile_update()

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/pmpro-aweber#5]
I've occasionally been getting unhandled exceptions when processing users. Whenever it happens, I forget to grab the stack tracer, but it looks - after a very quick review - as if `function pmproaw_profile_update($user_id, $old_user_data){}` is the only place where you're doing something with the AWeber API and you're not wrapping the activity in a try/catch pair.

**Comment by strangerstudios** [comment]
Should be fixed now.
