### ISSUE TITLE
double opt-in

### ISSUE THREAD

**Issue by kathrinbrand** [strangerstudios/pmpro-aweber#6]
Hi there,

I was looking forward to use this AWeber-plugin (which is great!). After doing a few tests I noticed that it is not possible to shut of double opt-in - if I use my AWeber account directly, I can do that though. Is there any way to shut it off for that plugin, too? it's important because otherwise I won't be using it in the future, just too much hassle for my subscribers... thanks a lot in advance! regards, Kathrin

**Comment by nvllsvm** [comment]
You need to contact AWeber support to disable confirmed opt-in. It is a limitation set by default for all lists and is different than the toggle you see in the AWeber control panel.

**Comment by strangerstudios** [comment]
@nvllsvm is correct. Will close this issue now.
